name: Build and Deploy Problems

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install platform-specific packages
        run: |
          npm install @rollup/rollup-linux-x64-gnu
          npm i --save-dev @types/node

      - name: Build challenges
        id: build-challenges
        run: |
          mkdir -p dist
          success_problems=()
          failed_problems=()

          build_problem() {
            local problem_name=$1

            echo "Building $problem_name"
            cd "$problem_name"

            if npm ci && npm run build; then
              mkdir -p ../../dist/problems/$problem_name
              cp -r dist/* ../../dist/problems/$problem_name/
              success_problems+=("$problem_name")
              echo "$problem_name build succeeded"
            else
              failed_problems+=("$problem_name")
              echo "$problem_name build failed"
            fi

            cd ../..
          }

          for problem in problems/*; do
            if [ -d "$problem" ]; then
              build_problem "$(basename "$problem")"
            fi
          done

          echo "Success: ${success_problems[@]}" >> $GITHUB_STEP_SUMMARY
          echo "Failed: ${failed_problems[@]}" >> $GITHUB_STEP_SUMMARY

      - name: Deploy to Vercel
        if: steps.build-challenges.outputs.success_problems != ""
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./dist
